version: '2.1'

services:
  frontend:
    build:
      ./tomcat
    ports:
      - "80:8080"
    volumes:
      - ./frontend/build/libs/frontend.war:/usr/local/tomcat/webapps/ROOT.war

  api:
    build:
      ./tomcat
    ports:
      - "9000:8080"
    volumes:
      - ./api/build/libs/api.war:/usr/local/tomcat/webapps/ROOT.war

  stream:
      build:
        ./tomcat
      ports:
        - "9001:8080"
      volumes:
        - ./stream/build/libs/stream.war:/usr/local/tomcat/webapps/ROOT.war

  classifier:
        build:
          ./tomcat
        ports:
          - "9002:8080"
        volumes:
          - ./classifier/build/libs/classifier.war:/usr/local/tomcat/webapps/ROOT.war

  db:
    build:
      ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: twitter_classification
      MYSQL_USER: twitter
      MYSQL_PASSWORD: password
      TZ: Europe/London
    ports:
      - "3307:3306"
    volumes:
      - ./db/db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  queue:
    build:
      ./queue
    hostname: "queue"
    ports:
      - "9004:15672"
      - "9005:5672"
    environment:
      RABBITMQ_DEFAULT_USER: twitter
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: "rabbitmqctl node_health_check | grep -q '^Health check passed' || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10

  queue-reader:
    image: frolvlad/alpine-java:jdk8-slim
    volumes:
      - ./queue-reader/build/libs/queue-reader-all.jar:/app.jar
    entrypoint: ["sh", "-c", "java -jar /app.jar"]
    depends_on:
      queue:
        condition: service_healthy

  pre-processor:
    build:
          ./tomcat
    ports:
      - "9003:8080"
    volumes:
      - ./pre-processor/build/libs/pre-processor.war:/usr/local/tomcat/webapps/ROOT.war
